# Generated by Django 3.1.3 on 2020-11-16 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maphandler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='robotmap',
            old_name='Map',
            new_name='map_image',
        ),
    ]
