# Generated by Django 3.1.3 on 2020-11-20 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maphandler', '0002_auto_20201116_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='robotmap',
            name='scale_x',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='robotmap',
            name='scale_y',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='robotmap',
            name='size_x',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='robotmap',
            name='size_y',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='RobotCoordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
                ('map_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maphandler.robotmap')),
            ],
        ),
    ]
