# Generated by Django 3.1.3 on 2020-11-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maphandler', '0004_auto_20201121_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robotmap',
            name='scale_x',
            field=models.FloatField(default=0, help_text='map horizontal scale in 1 pixel : xx meter'),
        ),
        migrations.AlterField(
            model_name='robotmap',
            name='scale_y',
            field=models.FloatField(default=0, help_text='map vertical scale in 1 pixel : xx meter'),
        ),
    ]
